/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DzContainer {
        "full": boolean;
    }
    interface DzHline {
    }
    interface DzModal {
        "active": string;
        "amimation": string;
        "buttonTitle": string;
        "closeModal": () => Promise<void>;
        "openModal": () => Promise<void>;
    }
    interface DzVline {
        "display": string;
        "offset": string;
        "rule": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLDzContainerElement extends Components.DzContainer, HTMLStencilElement {
    }
    var HTMLDzContainerElement: {
        prototype: HTMLDzContainerElement;
        new (): HTMLDzContainerElement;
    };
    interface HTMLDzHlineElement extends Components.DzHline, HTMLStencilElement {
    }
    var HTMLDzHlineElement: {
        prototype: HTMLDzHlineElement;
        new (): HTMLDzHlineElement;
    };
    interface HTMLDzModalElement extends Components.DzModal, HTMLStencilElement {
    }
    var HTMLDzModalElement: {
        prototype: HTMLDzModalElement;
        new (): HTMLDzModalElement;
    };
    interface HTMLDzVlineElement extends Components.DzVline, HTMLStencilElement {
    }
    var HTMLDzVlineElement: {
        prototype: HTMLDzVlineElement;
        new (): HTMLDzVlineElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "dz-container": HTMLDzContainerElement;
        "dz-hline": HTMLDzHlineElement;
        "dz-modal": HTMLDzModalElement;
        "dz-vline": HTMLDzVlineElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface DzContainer {
        "full"?: boolean;
    }
    interface DzHline {
    }
    interface DzModal {
        "active"?: string;
        "amimation"?: string;
        "buttonTitle"?: string;
    }
    interface DzVline {
        "display"?: string;
        "offset"?: string;
        "rule"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "dz-container": DzContainer;
        "dz-hline": DzHline;
        "dz-modal": DzModal;
        "dz-vline": DzVline;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dz-container": LocalJSX.DzContainer & JSXBase.HTMLAttributes<HTMLDzContainerElement>;
            "dz-hline": LocalJSX.DzHline & JSXBase.HTMLAttributes<HTMLDzHlineElement>;
            "dz-modal": LocalJSX.DzModal & JSXBase.HTMLAttributes<HTMLDzModalElement>;
            "dz-vline": LocalJSX.DzVline & JSXBase.HTMLAttributes<HTMLDzVlineElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
